In [5]:
import numpy as np
import pandas as pd 

In [17]:
df=pd.DataFrame([[8,8,4],[7,9,7],[5,12,17]],columns=['cgpa','profile_score','salary(lpa)'])

In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model=Sequential()

In [20]:
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\Ashish Kumar Singh\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.get_weights()

[array([[-1.1984642 , -0.19417024],
        [ 0.8814508 , -0.2680084 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.04269445],
        [ 1.2043065 ]], dtype=float32),
 array([0.], dtype=float32)]

In [25]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [34]:
model.fit(df.iloc[:,0:-1].values,df['salary(lpa)'].values,epochs=500,verbose=1,batch_size=1)

Epoch 1/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.4688  
Epoch 2/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.5905 
Epoch 3/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.5726 
Epoch 4/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.3586  
Epoch 5/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.5361 
Epoch 6/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0089 
Epoch 7/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.9067 
Epoch 8/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.8822 
Epoch 9/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.4604 
Epoch 10/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.4427 
Epoch 11/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.8375 
Epoch 12/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6329  
Epoch 13/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.8102 
Epoch 14/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.7850 
Epoch 15/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.7829 
Epoch 16/500
3/3

In [35]:
model.get_weights()

[array([[-1.4367495 , -0.12814231],
        [ 1.6346675 ,  0.3044207 ]], dtype=float32),
 array([0.32071176, 0.36497545], dtype=float32),
 array([[0.894288 ],
        [1.2854252]], dtype=float32),
 array([0.3776164], dtype=float32)]